### ISSUE TITLE
Hi,Can I add some settable parameters, such as the parameters in the figure below

### ISSUE THREAD

**Issue by baifagg** [uetuluk/disco-diffusion-ui#3]
Can I add some settable parameters, such as the parameters in the figure below? This is the gui version of disco diffusion provided by a Chinese website, but it only has the V5.2 version of disco diffusion. I want to convert the latest version of disco diffusion v5.61 to the gui version. What should I do
![image](https://user-images.githubusercontent.com/51266591/201457908-39039c90-d6f4-46be-8468-58e3209f9812.png)
![image](https://user-images.githubusercontent.com/51266591/201457918-8a1dd5c0-d8bf-4596-9bb7-d116f22d03ef.png)
![image](https://user-images.githubusercontent.com/51266591/201457924-8036521a-3149-4c58-ab82-d6c684b3e588.png)
![image](https://user-images.githubusercontent.com/51266591/201457933-d1a63422-e87f-4807-a446-5f769cac6b9e.png)

**Comment by uetuluk** [comment]
This GUI supports most of those options, if you require any additional configurations to be added, please request them separately. 

You need to setup Discoart as a service before using this UI.
